name: Upload Python Package

on:
  pull_request:
    types:
      - closed
      
defaults:
  run:
    working-directory: emanifest-py
  
jobs:
  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'runtest') && (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine
      - name: Build package
        run: python -m build
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --emanifest-wiljnich testpypi dist/*
